### ISSUE TITLE
Documentation for exploring

### ISSUE THREAD

**Issue by MGLL** [thomasdarimont/keycloak-opa-authz-demo#1]
Hi Thomas,
Thanks a lot for the demo at Keycloak Dev Days, 

Would it be possible to extend a bit the readme on how we can run this demo locally and play around? 

Like how OPA policies are packaged and stuff like that (I see `../target/keycloak-opa.jar:/opt/keycloak/providers/keycloak-opa.jar:z` so I suppose it's packaged and deployed in the provider folder of keycloak ?)

Thanks in advance

**Comment by LuciaCabanillasRodriguez** [comment]
Hi,

I completely agree with you. It would be great to have an expanded README. Furthermore, I attempted to deploy it myself and realized that the target folder with the keycloak-opa.jar was missing. 

Thanks in advance.

**Comment by MGLL** [comment]
Hi again @thomasdarimont, sorry to be a bit insistent, would it be possible to provide a bit of documentation to run it locally ?

Thanks

**Comment by LuciaCabanillasRodriguez** [comment]
Hi,

I am having some technical issues with that line `- ../target/keycloak-opa.jar:/opt/keycloak/providers/keycloak-opa.jar:z`

Thanks

**Comment by MGLL** [comment]
Thanks @thomasdarimont for the readme :) 
Would be happy to connect with you also, best regards
